export interface Food {
  id: number;
  name: string;
  description: string;
  ingredients: string;
  price: string;
  rating: number;
  image: string;
}

export const foods: Food[] = [
  {
    id: 1,
    name: "Osh",
    description: "An'anaviy o'zbek palovi, xushbo'y ziravorlar bilan.",
    ingredients: "Guruch, go'sht, sabzi, piyoz, yog', ziravorlar",
    price: "35 000 UZS",
    rating: 5.0,
    image: "/images/osh.jpg",
  },
  {
    id: 2,
    name: "Manti",
    description: "Bug'da pishirilgan, ichi go'sht va piyozga to'la manti.",
    ingredients: "Un, go'sht, piyoz, ziravorlar",
    price: "25 000 UZS",
    rating: 4.8,
    image: "/images/manti.jpg",
  },
  {
    id: 3,
    name: "Sho'rva mol gushtiga",
    description: "Mol go'shtidan tayyorlangan mazali va to'yimli sho'rva.",
    ingredients: "Mol go'shti, kartoshka, sabzi, piyoz, pomidor",
    price: "28 000 UZS",
    rating: 4.7,
    image: "/images/mol go'shtiga shorva.jpg",
  },
  {
    id: 4,
    name: "Sho'rva qo'y gushtiga",
    description: "Qo'y go'shtidan maxsus retsept asosida tayyorlangan sho'rva.",
    ingredients: "Qo'y go'shti, kartoshka, sabzi, no'xat",
    price: "30 000 UZS",
    rating: 4.9,
    image: "/images/qo'y goshtiga sho'rva.jpg",
  },
  {
    id: 5,
    name: "Tovuq shorva",
    description: "Yengil va shifobaxsh tovuq sho'rvasi.",
    ingredients: "Tovuq go'shti, ugra, sabzi, ko'katlar",
    price: "22 000 UZS",
    rating: 4.6,
    image: "/images/tovuk-shurpa.jpg",
  },
  {
    id: 6,
    name: "Uyg'ur lagmon",
    description: "Qo'lda cho'zilgan xamir va maxsus qayladan iborat uyg'urcha lag'mon.",
    ingredients: "Xamir, go'sht, sabzavotlar, maxsus ziravorlar",
    price: "32 000 UZS",
    rating: 4.9,
    image: "/images/uy'gurlag'mon.png",
  },
  {
    id: 7,
    name: "Qovurma lagmon",
    description: "Qovurib pishirilgan xamir va mazali go'shtli qayla.",
    ingredients: "Xamir, go'sht, sabzavotlar, tomat",
    price: "30 000 UZS",
    rating: 4.8,
    image: "/images/qovurma lag'mon.jpg",
  },
  {
    id: 8,
    name: "Oddiy lagmon",
    description: "Suyuq qaylali an'anaviy o'zbekcha lag'mon.",
    ingredients: "Xamir, go'sht, kartoshka, sabzi",
    price: "26 000 UZS",
    rating: 4.5,
    image: "/images/oddiy lag'mon.png",
  },
  {
    id: 9,
    name: "Bifshteks",
    description: "Yumshoq qilib qovurilgan lahm go'sht.",
    ingredients: "Mol go'shti, tuxum, qovurilgan kartoshka",
    price: "40 000 UZS",
    rating: 4.7,
    image: "/images/bifshteks.jpg",
  },
  {
    id: 10,
    name: "Sokoro",
    description: "Maxsus retsept bilan tayyorlangan shirin go'shtli taom.",
    ingredients: "Go'sht, sabzavotlar, sous",
    price: "38 000 UZS",
    rating: 4.6,
    image: "/images/sokoro.jpg",
  },
  {
    id: 11,
    name: "Gushtsay",
    description: "Go'sht va sabzavotlardan qovurilgan mazali taom.",
    ingredients: "Go'sht, bulg'or qalampiri, piyoz, pomidor",
    price: "35 000 UZS",
    rating: 4.8,
    image: "/images/go'shtsay.jpg",
  },
  {
    id: 12,
    name: "Tushonka",
    description: "Uzoq vaqt dimlab pishirilgan yumshoq go'sht.",
    ingredients: "Go'sht, piyoz, maxsus sous",
    price: "45 000 UZS",
    rating: 4.9,
    image: "/images/tushonka.png",
  },
  {
    id: 13,
    name: "Kuza shurva",
    description: "Maxsus sopol kuzada dimlab pishirilgan sho'rva.",
    ingredients: "Go'sht, sabzavotlar, no'xat",
    price: "32 000 UZS",
    rating: 4.8,
    image: "/images/ko'zasho'rva.jpg",
  },
  {
    id: 14,
    name: "Qotirma",
    description: "Qizib turgan qozonda qovurilgan qarsildoq go'sht.",
    ingredients: "Go'sht, yog', piyoz",
    price: "36 000 UZS",
    rating: 4.7,
    image: "/images/qotirma.png",
  },
  {
    id: 15,
    name: "Siltama",
    description: "Dimlab pishirilgan sersharbat go'shtli taom.",
    ingredients: "Go'sht, piyoz, pomidor, ziravorlar",
    price: "34 000 UZS",
    rating: 4.6,
    image: "/images/siltama.jpg",
  },
  {
    id: 16,
    name: "Shashlik qiyma",
    description: "Ko'mirda pishirilgan mayin qiyma shashlik.",
    ingredients: "Qiyma qilingan go'sht, piyoz, ziravorlar",
    price: "12 000 UZS",
    rating: 4.9,
    image: "/images/shashlik qiyma.png",
  },
  {
    id: 17,
    name: "Shashlik turgamchi",
    description: "Maxsus marinadlangan lahm shashlik.",
    ingredients: "Lahm go'sht, dumba, marinad",
    price: "15 000 UZS",
    rating: 5.0,
    image: "/images/shashlikto'rg'amchi.jpg",
  },
  {
    id: 18,
    name: "Somsa",
    description: "Tandirda yopilgan qarsildoq, sersharbat somsa.",
    ingredients: "Xamir, go'sht, piyoz, dumba",
    price: "8 000 UZS",
    rating: 4.8,
    image: "/images/somsa.jpg",
  },
  {
    id: 19,
    name: "Non",
    description: "Issiq, tandirdan uzilgan o'zbek noni.",
    ingredients: "Un, suv, tuz, xamirturush",
    price: "4 000 UZS",
    rating: 5.0,
    image: "/images/non.jpg",
  }
];
